// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8jgKcDwyyj5KDBQuvW_efklcbOdjsy64',
    appId: '1:147647359989:web:b8a1ce9afb170f47420ebc',
    messagingSenderId: '147647359989',
    projectId: 'login-flutter-f5a90',
    authDomain: 'login-flutter-f5a90.firebaseapp.com',
    storageBucket: 'login-flutter-f5a90.firebasestorage.app',
    measurementId: 'G-F21EZ0F6VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMUC9LfAfpWt_DZM1JAkNu_HVyjOtz43U',
    appId: '1:147647359989:android:e1c31f65b3265667420ebc',
    messagingSenderId: '147647359989',
    projectId: 'login-flutter-f5a90',
    storageBucket: 'login-flutter-f5a90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhogTYyCwFW1sO3swU2_Xoy6nOrXK26OE',
    appId: '1:147647359989:ios:96ecb7e940d05acf420ebc',
    messagingSenderId: '147647359989',
    projectId: 'login-flutter-f5a90',
    storageBucket: 'login-flutter-f5a90.firebasestorage.app',
    iosBundleId: 'com.example.uasMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhogTYyCwFW1sO3swU2_Xoy6nOrXK26OE',
    appId: '1:147647359989:ios:96ecb7e940d05acf420ebc',
    messagingSenderId: '147647359989',
    projectId: 'login-flutter-f5a90',
    storageBucket: 'login-flutter-f5a90.firebasestorage.app',
    iosBundleId: 'com.example.uasMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8jgKcDwyyj5KDBQuvW_efklcbOdjsy64',
    appId: '1:147647359989:web:15b891308ddf8c48420ebc',
    messagingSenderId: '147647359989',
    projectId: 'login-flutter-f5a90',
    authDomain: 'login-flutter-f5a90.firebaseapp.com',
    storageBucket: 'login-flutter-f5a90.firebasestorage.app',
    measurementId: 'G-5MY66VEKL9',
  );
}
